name: nisar-py
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.11,<3.14
  - pip
  # For packaging, and testing
  - setuptools_scm
  - pytest
  - pytest-cov
  - xarray
  - h5netcdf
  # For running
  - isce3
  - libgdal-hdf5
  - numpy
  - pystac
  - pip:
      - -r requirements.txt
      - -r requirements-static.txt
