name: nisar-py
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.11,<3.15
  - pip
  # For packaging, and testing
  - setuptools_scm
  - pytest
  - pytest-cov
  # For running
  - dask
  - gdal
  - pystac
  - xarray
  - h5netcdf
  - pip:
      - -r requirements.txt
      - -r requirements-static.txt
